### ISSUE TITLE
infergriddef - 2D data Problem

### ISSUE THREAD

**Issue by Thiago-Reis-Porto** [CcgAlberta/pygeostat#31]
Hi, I think I have found a problem with the "infergriddef" method, if an Integer is passed to the "nblk" parameter. With an integer, the nz will never be none and "twod" will be False, raising an exception if it's an 2D data.

![image](https://user-images.githubusercontent.com/42750555/144690943-c73f44c1-742e-418f-be22-48a3de5a42aa.png)

Also, the same happens with float or if the z value is passed as 1 on the blksize. So the documentation example doesn't work.
![image](https://user-images.githubusercontent.com/42750555/144691210-c09340d6-b829-45a9-8e25-d469cd79ca6e.png)

**Comment by zahrahadavand** [comment]
In docstring of "pygeostat/data.py/infergriddef", this is mentioned that:
"If data is 2-D, zsiz or nz must be provided as None. Otherwise it raise exception:"
The examples have been corrected in the documentation: (the corrected examples in the docstring will be updated to the next release of pygeostat)
				df2d = gs.ExampleData("point2d_ind")
				df2d.infergriddef(nblk = [60, 60, None])
				df2d.infergriddef(blksize = [50,60,None])
